config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(:id)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params())
    if @article.save
      redirect_to @article
    else
      flash[:notice] = 'error'
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= form_with model: @article, url: articles_path, local: true,class: 'form-horizontal' do |form| %>
     <% @article.errors.full_messages.each do |msg| %>
         <div class="alert alert-danger" role="alert"><%= msg %></div>
        <% end %>

<div class="form-group">
    <label for="articl_title" class="col-sm-2 control-label">title</label>
    <div class="col-sm-10">
    <%= form.text_field :title, class: 'form-control' %>
    </div>
</div>
  
 <div class="form-group">
    <label for="articl_title" class="col-sm-2 control-label">text</label>
    <div class="col-sm-10">
      <%= form.text_area :text , class: 'form-control' %>
    </div>
  </div>
 <div class="form-group">
    <div class ='col-sm-10'>
        <%= form.submit class: 'btn btn-primary'%>
    </div>
 <div class="form-group">
<% end %>
<%= link_to 'Back', articles_path, role:'button' %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<table class ='table table-hover'>
  <tr class = "info">
    <th>Title</th>
    <th>Text</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>
 
 <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1 class = "text-info">New Article</h1>
<%= form_with scope: :article, url: articles_path, local: true,class: 'form-horizontal' do |form| %>
  <div class="form-group">
    <label for="articl_title" class="col-sm-2 control-label">title</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" id="articl_title" placeholder="title" name="article[title]">
    </div>
  </div>
  
 <div class="form-group">
    <label for="articl_title" class="col-sm-2 control-label">text</label>
    <div class="col-sm-10">
        <textarea type="text_area" class="form-control" id="articl_title" placeholder="title" name="article[text]">
        </textarea>
    </div>
  </div>
 <div class="form-group">
    <div class ='col-sm-10'>
        <%= form.submit class: 'btn btn-primary'%>
    </div>
 <div class="form-group">
<% end %>
<%= link_to 'Back', articles_path, role:'button' %>

app/views/articles/show.html.erb
<div class="form-group">
    <p class="bg-primary text-warning">
      <strong>Title:</strong>
      <%= @article.title %>
    </p>
     
    <p class="bg-primary text-warning">
      <strong>Text:</strong>
      <%= @article.text %>
    </p>
    <%= link_to 'Back', articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnRubyOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = 'container'>
      <%= yield %>
    </div>
  
  </body>
   <%= javascript_include_tag 'articles', 'data-turbolinks-track': 'reload' %>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>